name = "StagPP"
uuid = "1e4af5fc-12d6-46af-bf26-017dd3cc6e9d"
version = "1.0.0-DEV"
authors = ["Nickolas Moccetti Bardi <99484637+Nickmotb@users.noreply.github.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MAGEMin_C = "e5d170eb-415a-4524-987b-12f1bce1ddab"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CairoMakie = "0.15.6"
ColorSchemes = "3.31.0"
DelimitedFiles = "1.9.1"
EasyFit = "0.7.2"
ForwardDiff = "1.2.2"
GLMakie = "0.13.6"
Interpolations = "0.16.2"
LightXML = "0.9.3"
LinearAlgebra = "1.12.0"
LsqFit = "0.15.1"
MAGEMin_C = "2.1.3"
Mmap = "1.11.0"
MultivariateStats = "0.10.3"
Parsers = "2.8.3"
Printf = "1.11.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
StatsBase = "0.34.9"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
